/* Shared identity views; product data and permissions remain separate. */
const businessNames = {service:'客户日常服务',placement:'定增',priority:'优先劣后',legacy:'历史跟进 · 未分类'};
let workspaceBusiness = '';
const workspaceTime = value => value ? new Date(value).toLocaleString('zh-CN', {hour12:false}) : '—';
const placementViews = new Set(['placement','customers','imports','reviews','assignments','bindings','fields']);
function workspaceNavigation() {
  return `<div class="nav-caption">日常工作</div><nav class="nav">${navButton('dashboard','⌗','工作台',state.view==='dashboard')}${navButton('followups','◌','我的跟进',state.view==='followups')}</nav><div class="nav-caption">客户中心</div><nav class="nav">${navButton('directory','▦','全部客户',state.view==='directory')}</nav><div class="nav-caption">产品业务</div><nav class="nav product-nav">${navButton('placement','◈','定增',placementViews.has(state.view))}${navButton('priority','▤','优先劣后',state.view==='priority')}</nav><div class="nav-caption">系统管理</div><nav class="nav">${state.user.canManageCrmPermissions?navButton('permissions','⚙','人员与权限',state.view==='permissions')+navButton('audit','≡','操作日志',state.view==='audit'):'<span class="hint">由管理员维护</span>'}</nav>`;
}
function placementNavigation(content) {
  if (!placementViews.has(state.view)) return;
  const tabs=[['placement','批次管理',true],['customers','业务客户',true],['imports','资料录入',true],['reviews','导入复核',state.user.canImportCustomers||state.user.canManageCrmPermissions],['assignments','负责人分配',state.user.canManageAssignments],['bindings','经纪人绑定',state.user.canManageAdvisorBindings],['fields','业务表头',state.user.canManageCustomerFields]];
  content.insertAdjacentHTML('beforebegin',`<div class="business-context" id="business-navigation"><span>产品业务 / 定增</span><h3>定增业务</h3><p>批次、业务进度、资料录入与负责人分配。</p><nav class="workspace-tabs">${tabs.filter(t=>t[2]).map(([key,label])=>`<button class="${state.view===key?'active':''}" data-product-view="${key}">${label}</button>`).join('')}<button id="placement-followups">业务跟进</button></nav></div>`);
  document.querySelector('#business-navigation').querySelectorAll('[data-product-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.productView));
  document.querySelector('#placement-followups').onclick=()=>{workspaceBusiness='placement';navigate('followups');};
}
function noteMarkup(rows) {
  return rows.map(r=>`<article class="workspace-note"><div class="timeline-head"><strong>${esc(businessNames[r.business])}${r.batch_key?` · 批次 ${esc(r.batch_key)}`:''}</strong><span>${esc(r.author_name)} · ${workspaceTime(r.created_at)}</span></div><p>${esc(r.content)}</p>${r.outcome?`<p>结果：${esc(r.outcome)}</p>`:''}${r.next_action?`<p>下一步：${esc(r.next_action)}</p>`:''}${r.next_followup_at?`<p>下次联系：${workspaceTime(r.next_followup_at)}${r.completed_at?' · 已完成':r.legacy?' · 历史计划（完成状态未知）':' · 待完成'}</p>`:''}</article>`).join('')||'<div class="empty">暂无跟进记录</div>';
}
async function renderCustomerDirectory(content) {
  const data=await api('/api/workspace/customers');
  content.innerHTML=`<div class="section-heading"><div><div class="eyebrow">客户中心</div><h3>全部客户</h3><p>按 TW 汇总身份；只展示你有权查看的业务资料。业务可见不代表已经参与。</p></div></div><section class="section"><div class="workspace-toolbar"><input id="directory-search" type="search" value="${esc(state.search)}" placeholder="搜索姓名或 TW" aria-label="搜索客户"><select id="directory-business" aria-label="业务范围"><option value="">全部可见客户</option><option value="placement">定增业务可见</option><option value="priority">优先劣后业务可见</option></select><span id="directory-count"></span></div><div class="table-wrap"><table><thead><tr><th>客户</th><th>TW</th><th>定增负责人</th><th>优先劣后负责人</th><th>操作</th></tr></thead><tbody id="directory-rows"></tbody></table></div></section>`;
  const update=()=>{
    const q=content.querySelector('#directory-search').value.trim().toLowerCase(), business=content.querySelector('#directory-business').value;
    const rows=data.items.filter(p=>(!q||[p.name,p.twCode,...(p.searchTerms||[])].some(v=>v.toLowerCase().includes(q)))&&(!business||p.businesses.includes(business)));
    content.querySelector('#directory-count').textContent=`${rows.length} 位客户 / 待匹配记录`;
    content.querySelector('#directory-rows').innerHTML=rows.map((p,i)=>`<tr><td>${esc(p.name)}</td><td>${esc(p.twCode||'身份待确认')}</td><td>${esc(p.placementOwner||'—')}</td><td>${esc(p.priorityOwner||'—')}</td><td><button class="p-link" data-card="${i}">客户卡片</button><button class="p-link" data-note="${i}">写跟进</button></td></tr>`).join('')||'<tr><td colspan="5">暂无符合条件的客户</td></tr>';
    content.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>openCustomerCard(rows[Number(b.dataset.card)].key));
    content.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>openWorkspaceNote(rows[Number(b.dataset.note)].key));
  };
  content.querySelector('#directory-search').oninput=update;content.querySelector('#directory-business').onchange=update;update();
}
async function openCustomerCard(key) {
  try {
    const p=await api(`/api/workspace/card?key=${encodeURIComponent(key)}`);
    const table=(rows,cols)=>`<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c[0]]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    openModal(`<div class="modal p-modal"><div class="modal-header"><div><h3>${esc(p.name)}</h3><span>${esc(p.twCode||'身份待确认')} · 客户卡片</span></div><button class="close-btn" data-close>×</button></div><div class="modal-body"><div class="workspace-toolbar">${p.businesses.map(b=>`<button class="secondary-btn" data-card-note="${b}">写${businessNames[b]}跟进</button>`).join('')}</div><h4>基本资料</h4>${p.crm.length?table(p.crm,[['phone','电话'],['email','邮箱'],['account_status','券商开户']]):'<p>联系方式尚未提供或不在当前可见范围。</p>'}<h4>定增</h4>${p.crm.map(c=>`<button class="p-link" data-placement-detail="${esc(c.id)}">查看 / 编辑定增资料</button>`).join('')}${p.crm.length?table(p.crm,[['owner_name','负责人'],['placement_status','业务状态']])+table(p.placementBatches,[['batch_name','参与批次'],['status','参与状态']]):'<p>暂无可见的定增业务资料。</p>'}<h4>优先劣后</h4>${p.priority.length?table(p.priority,[['date','批次日期'],['agreementAmountUsd','协议金额 USD'],['insuranceBroker','保险经纪人'],['serviceOwner','当前服务负责人']]):'<p>暂无可见的优先劣后业务资料。</p>'}${p.priority.length&&p.twCode?'<button class="p-link" id="card-source-history">查看原始业务历史与来源</button>':''}<h4>资产与 XMax 持仓历史</h4>${p.assets.length?table(p.assets,[['date','资产资料日期'],['assetUsd','总资产 USD']]):'<p>暂无可见资产资料。</p>'}${p.secondary.length?table(p.secondary,[['date','持仓资料日期'],['quantity','XMax 股数']]):'<p>暂无可见持仓资料。</p>'}<h4>跟进时间线</h4><select id="card-note-filter" aria-label="跟进业务"><option value="">全部可见记录</option>${Object.entries(businessNames).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><div id="card-notes">${noteMarkup(p.followups)}</div></div></div>`);
    document.querySelector('#card-source-history')?.addEventListener('click',()=>{closeModal();priorityCustomerHistoryLegacy(p.twCode);});
    document.querySelectorAll('[data-placement-detail]').forEach(b=>b.onclick=()=>{closeModal();openDetail(b.dataset.placementDetail);});
    document.querySelectorAll('[data-card-note]').forEach(b=>b.onclick=()=>{closeModal();openWorkspaceNote(p.key,b.dataset.cardNote);});
    document.querySelector('#card-note-filter').onchange=e=>{document.querySelector('#card-notes').innerHTML=noteMarkup(p.followups.filter(r=>!e.target.value||r.business===e.target.value));};
  }catch(err){toast(err.message);}
}
async function openWorkspaceNote(key='', business='service', batch='') {
  try {
    const {items}=await api('/api/workspace/customers');
    if (key.startsWith('crm:')) key=items.find(p=>p.crmIds.includes(key.slice(4)))?.key||key;
    let selected=items.find(p=>p.key===key), card=null;
    openModal(`<div class="modal"><div class="modal-header"><h3>写工作跟进</h3><button class="close-btn" data-close>×</button></div><form id="workspace-note-form"><div class="modal-body"><div class="field"><label for="note-search">搜索客户</label><input id="note-search" type="search" placeholder="姓名或 TW"></div><div class="field"><label for="note-person">客户</label><select id="note-person" required><option value="">请选择</option></select></div><div class="form-grid"><div class="field"><label for="note-business">所属业务</label><select name="business" id="note-business" required></select></div><div class="field"><label for="note-batch">关联批次（可选）</label><select name="batchKey" id="note-batch"><option value="">不关联批次</option></select></div><div class="field"><label>沟通方式</label><select name="method">${(state.meta.followupMethods||['电话','微信','面谈']).map(v=>`<option>${esc(v)}</option>`).join('')}</select></div></div><div class="field"><label>沟通内容 *</label><textarea name="content" required maxlength="10000"></textarea></div><div class="field"><label>沟通结果</label><input name="outcome" maxlength="2000"></div><div class="field"><label>下一步动作</label><input name="nextAction" maxlength="2000"></div><div class="field"><label>下次联系时间</label><input name="nextFollowupAt" type="datetime-local"></div><p id="note-error" class="p-error" role="alert"></p></div><div class="modal-footer"><button class="secondary-btn" type="button" data-close>取消</button><button class="primary-btn" id="note-save" disabled>保存跟进</button></div></form></div>`);
    const form=document.querySelector('#workspace-note-form'), picker=form.querySelector('#note-person'), biz=form.querySelector('#note-business');
    const fill=()=>{const q=form.querySelector('#note-search').value.trim().toLowerCase();picker.innerHTML='<option value="">请选择</option>'+items.filter(p=>p.key===selected?.key||!q||[p.name,p.twCode,...(p.searchTerms||[])].some(v=>v.toLowerCase().includes(q))).map(p=>`<option value="${esc(p.key)}" ${p.key===selected?.key?'selected':''}>${esc(p.name)} · ${esc(p.twCode||'待确认身份')}</option>`).join('');};
    const batches=()=>{let options=[];if(card&&biz.value==='priority')options=[...new Set(card.priority.map(r=>r.date))].map(v=>[v,v]);if(card&&biz.value==='placement'){options=card.placementBatches.map(r=>[r.batch_id,r.batch_name]);for(const c of card.crm)if(c.target_batch_id&&!options.some(r=>r[0]===c.target_batch_id))options.push([c.target_batch_id,'当前目标批次']);}form.querySelector('#note-batch').innerHTML='<option value="">不关联批次</option>'+options.map(([v,l])=>`<option value="${esc(v)}" ${v===batch?'selected':''}>${esc(l)}</option>`).join('');};
    let request=0;
    const choose=async()=>{const seq=++request;selected=items.find(p=>p.key===picker.value);card=null;form.querySelector('#note-save').disabled=true;biz.innerHTML=(selected?.businesses||[]).map(b=>`<option value="${b}" ${b===business?'selected':''}>${businessNames[b]}</option>`).join('');batches();if(selected){try{const result=await api(`/api/workspace/card?key=${encodeURIComponent(selected.key)}`);if(seq!==request)return;card=result;batches();form.querySelector('#note-save').disabled=false;}catch(err){form.querySelector('#note-error').textContent=err.message;}}};
    fill();form.querySelector('#note-search').oninput=fill;picker.onchange=choose;biz.onchange=()=>{business=biz.value;batch='';batches();};await choose();
    form.onsubmit=async e=>{e.preventDefault();if(!selected||!card)return;const button=form.querySelector('#note-save');setBusyButton(button,true);const values=Object.fromEntries(new FormData(form));values.subjectKey=selected.key;values.nextFollowupAt=values.nextFollowupAt?new Date(values.nextFollowupAt).toISOString():null;try{await api('/api/workspace/followups',{method:'POST',body:JSON.stringify(values)});closeModal();toast('跟进已保存');if(state.view==='followups'||state.view==='dashboard')await navigate(state.view);else await openCustomerCard(selected.key);}catch(err){form.querySelector('#note-error').textContent=err.message;setBusyButton(button,false);}};
  }catch(err){toast(err.message);}
}
async function renderUnifiedFollowups(content) {
  const {items}=await api('/api/workspace/followups');
  content.innerHTML=`<div class="section-heading"><div><div class="eyebrow">日常工作</div><h3>我的跟进</h3><p>同一份记录，按客户与业务查看。历史记录保留为未分类，不自动归入定增。</p></div><button class="primary-btn" id="workspace-add-note">＋ 写跟进</button></div><section class="section"><div class="workspace-toolbar"><select id="work-business" aria-label="业务筛选"><option value="">全部业务</option>${Object.entries(businessNames).map(([k,v])=>`<option value="${k}" ${workspaceBusiness===k?'selected':''}>${v}</option>`).join('')}</select><select id="work-author" aria-label="跟进范围"><option value="mine">我记录的</option><option value="all">全部可见</option></select><select id="work-status" aria-label="待办状态"><option value="">全部记录</option><option value="due">已到期待办</option><option value="open">未完成待办</option><option value="done">已完成待办</option></select><input type="search" id="work-search" placeholder="搜索客户或沟通内容"><span id="work-count"></span></div><div id="work-records"></div></section>`;
  const update=()=>{workspaceBusiness=content.querySelector('#work-business').value;const status=content.querySelector('#work-status').value,q=content.querySelector('#work-search').value.trim().toLowerCase();const rows=items.filter(r=>(!workspaceBusiness||r.business===workspaceBusiness)&&(content.querySelector('#work-author').value==='all'||r.author_id===state.user.id)&&(!q||[r.customer_name,r.tw_code,r.content].some(v=>(v||'').toLowerCase().includes(q)))&&(!status||(!r.legacy&&r.next_followup_at&&(status==='done'?r.completed_at:!r.completed_at&&(status==='open'||new Date(r.next_followup_at)<=new Date())))));content.querySelector('#work-count').textContent=`${rows.length} 条`;content.querySelector('#work-records').innerHTML=rows.map((r,i)=>`<div class="workspace-followup"><div class="workspace-toolbar"><button class="p-link" data-work-card="${i}">${esc(r.customer_name)} · ${esc(r.tw_code||'身份待确认')}</button><button class="p-link" data-work-note="${i}">继续跟进</button>${!r.legacy&&r.next_followup_at&&!r.completed_at?`<button class="secondary-btn" data-work-complete="${i}">标记待办完成</button>`:''}</div>${noteMarkup([r])}</div>`).join('')||'<div class="empty">当前筛选下暂无跟进</div>';content.querySelectorAll('[data-work-card]').forEach(b=>b.onclick=()=>openCustomerCard(rows[+b.dataset.workCard].subject_key));content.querySelectorAll('[data-work-note]').forEach(b=>b.onclick=()=>{const r=rows[+b.dataset.workNote];openWorkspaceNote(r.subject_key,r.legacy?'service':r.business,r.batch_key);});content.querySelectorAll('[data-work-complete]').forEach(b=>b.onclick=async()=>{setBusyButton(b,true);try{await api(`/api/workspace/followups/${rows[+b.dataset.workComplete].id}/complete`,{method:'POST'});await renderUnifiedFollowups(content);}catch(err){toast(err.message);setBusyButton(b,false);}});};
  ['work-business','work-author','work-status'].forEach(id=>content.querySelector('#'+id).onchange=update);content.querySelector('#work-search').oninput=update;content.querySelector('#workspace-add-note').onclick=()=>openWorkspaceNote('',workspaceBusiness==='legacy'?'service':workspaceBusiness||'service');update();
}
async function workspaceDashboard(content) {
  const {items}=await api('/api/workspace/followups');
  const due=items.filter(r=>!r.legacy&&r.author_id===state.user.id&&r.next_followup_at&&!r.completed_at&&new Date(r.next_followup_at)<=new Date());
  content.insertAdjacentHTML('afterbegin',`<section class="workspace-home"><button data-home="placement"><small>产品业务</small><strong>定增 →</strong><span>批次与业务推进</span></button><button data-home="priority"><small>产品业务</small><strong>优先劣后 →</strong><span>协议、资料与客户服务</span></button><button data-home="followups"><small>我的跟进</small><strong>${due.length} 项到期待办 →</strong><span>日常服务及两个业务统一查看</span></button></section><p class="hint">下方经营统计沿用原定增客户口径；优先劣后统计请进入对应板块。</p>`);
  content.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>{workspaceBusiness='';navigate(b.dataset.home);});
}

async function refreshDrawerWorkspace(id) {
  const drawer=document.querySelector('#detail-drawer');
  if(!drawer)return;
  drawer.querySelector('.detail-actions').insertAdjacentHTML('afterbegin','<button class="secondary-btn" id="drawer-shared-card">客户卡片</button>');
  drawer.querySelector('#drawer-shared-card').onclick=()=>{closeDrawer();openCustomerCard('crm:'+id);};
  try {
    const p=await api('/api/workspace/card?key='+encodeURIComponent('crm:'+id));
    if(drawer.isConnected)drawer.querySelector('.timeline').innerHTML=noteMarkup(p.followups.filter(r=>['placement','service','legacy'].includes(r.business)));
  }catch(err){if(drawer.isConnected)toast(err.message);}
}
