"""PostgreSQL schema for the customer module.

Timestamps remain text intentionally: existing records are ISO-8601 strings and the
application already serializes them that way. This keeps the SQLite-to-PostgreSQL data
migration lossless while preserving the existing API contract.
"""

from __future__ import annotations

POSTGRES_SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS module_sessions (
        token TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        created_at TEXT NOT NULL,
        expires_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sso_handoffs (
        handoff_id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        consumed_at TEXT NOT NULL,
        expires_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_permissions (
        user_id TEXT PRIMARY KEY,
        can_import_customers INTEGER,
        can_export_all INTEGER,
        can_manage_customer_fields INTEGER,
        scope_override TEXT,
        can_manage_assignments INTEGER,
        can_manage_advisor_bindings INTEGER,
        can_manage_crm_permissions INTEGER,
        updated_by TEXT,
        updated_at TEXT NOT NULL
    )
    """,
    "ALTER TABLE user_permissions ADD COLUMN IF NOT EXISTS scope_override TEXT",
    "ALTER TABLE user_permissions ADD COLUMN IF NOT EXISTS can_manage_assignments INTEGER",
    "ALTER TABLE user_permissions ADD COLUMN IF NOT EXISTS can_manage_advisor_bindings INTEGER",
    "ALTER TABLE user_permissions ADD COLUMN IF NOT EXISTS can_manage_crm_permissions INTEGER",
    """
    CREATE TABLE IF NOT EXISTS counters (
        counter_key TEXT PRIMARY KEY,
        counter_value INTEGER NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS customers (
        id TEXT PRIMARY KEY,
        customer_code TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        phone TEXT NOT NULL DEFAULT '',
        email TEXT NOT NULL DEFAULT '',
        company TEXT NOT NULL DEFAULT '',
        source TEXT NOT NULL DEFAULT '',
        source_detail TEXT NOT NULL DEFAULT '',
        stage TEXT NOT NULL DEFAULT '待联系',
        priority TEXT NOT NULL DEFAULT '普通',
        owner_id TEXT NOT NULL,
        owner_name TEXT NOT NULL,
        owner_team TEXT NOT NULL,
        notes TEXT NOT NULL DEFAULT '',
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        import_job_id TEXT,
        archived_at TEXT,
        merged_into_id TEXT,
        version INTEGER NOT NULL DEFAULT 1,
        account_status TEXT NOT NULL DEFAULT '未启动',
        account_broker TEXT NOT NULL DEFAULT '',
        account_opened_at TEXT,
        intent_status TEXT NOT NULL DEFAULT '未确认',
        placement_status TEXT NOT NULL DEFAULT '未进入',
        target_batch_id TEXT,
        intent_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
        funded_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
        actual_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
        lost_reason TEXT NOT NULL DEFAULT '',
        closed_at TEXT,
        hongan_advisor TEXT NOT NULL DEFAULT '',
        source_advisor_label TEXT NOT NULL DEFAULT '',
        broker_deposit_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
        capital_destination TEXT NOT NULL DEFAULT '',
        wechat_nickname TEXT NOT NULL DEFAULT '',
        CONSTRAINT customers_merged_into_fk
            FOREIGN KEY (merged_into_id) REFERENCES customers(id) DEFERRABLE INITIALLY DEFERRED
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_customers_owner ON customers(owner_id, archived_at)",
    "CREATE INDEX IF NOT EXISTS idx_customers_team ON customers(owner_team, archived_at)",
    "CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(name)",
    "ALTER TABLE customers ADD COLUMN IF NOT EXISTS import_job_id TEXT",
    "CREATE INDEX IF NOT EXISTS idx_customers_import_job ON customers(import_job_id, archived_at)",
    """
    CREATE TABLE IF NOT EXISTS customer_identifiers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_id TEXT NOT NULL REFERENCES customers(id) DEFERRABLE INITIALLY DEFERRED,
        kind TEXT NOT NULL,
        normalized_value TEXT NOT NULL,
        display_value TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(kind, normalized_value)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS assignments (
        id TEXT PRIMARY KEY,
        customer_id TEXT NOT NULL REFERENCES customers(id) DEFERRABLE INITIALLY DEFERRED,
        from_owner_id TEXT,
        from_owner_name TEXT,
        from_team TEXT,
        to_owner_id TEXT NOT NULL,
        to_owner_name TEXT NOT NULL,
        to_team TEXT NOT NULL,
        reason TEXT NOT NULL,
        changed_by TEXT NOT NULL,
        changed_by_name TEXT NOT NULL,
        changed_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS customer_collaborators (
        customer_id TEXT NOT NULL REFERENCES customers(id) DEFERRABLE INITIALLY DEFERRED,
        user_id TEXT NOT NULL,
        user_name TEXT NOT NULL,
        user_team TEXT NOT NULL,
        collaborator_role TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        PRIMARY KEY (customer_id, user_id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_customer_collaborators_user ON customer_collaborators(user_id, customer_id)",
    """
    CREATE TABLE IF NOT EXISTS advisor_alias_mappings (
        alias TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        user_name TEXT NOT NULL,
        user_team TEXT NOT NULL,
        updated_by TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_advisor_alias_mappings_alias_ci ON advisor_alias_mappings(lower(alias))",
    """
    CREATE TABLE IF NOT EXISTS advisor_bindings (
        id TEXT PRIMARY KEY,
        hongan_advisor TEXT NOT NULL,
        jiaoyang_advisor_label TEXT NOT NULL,
        jiaoyang_advisor_id TEXT,
        customer_type TEXT NOT NULL CHECK(customer_type IN ('non_placement', 'placement')),
        assignment_mode TEXT NOT NULL CHECK(assignment_mode IN ('default', 'manual')),
        active INTEGER NOT NULL DEFAULT 1,
        notes TEXT NOT NULL DEFAULT '',
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_by TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_advisor_bindings_unique_ci ON advisor_bindings(lower(hongan_advisor), customer_type, assignment_mode)",
    "CREATE INDEX IF NOT EXISTS idx_advisor_bindings_lookup ON advisor_bindings(hongan_advisor, customer_type, assignment_mode, active)",
    """
    CREATE TABLE IF NOT EXISTS followups (
        id TEXT PRIMARY KEY,
        customer_id TEXT NOT NULL REFERENCES customers(id) DEFERRABLE INITIALLY DEFERRED,
        author_id TEXT NOT NULL,
        author_name TEXT NOT NULL,
        method TEXT NOT NULL,
        content TEXT NOT NULL,
        outcome TEXT NOT NULL DEFAULT '',
        next_action TEXT NOT NULL DEFAULT '',
        next_followup_at TEXT,
        stage_after TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_followups_customer ON followups(customer_id, created_at DESC)",
    """
    CREATE TABLE IF NOT EXISTS merge_events (
        id TEXT PRIMARY KEY,
        source_customer_id TEXT NOT NULL,
        target_customer_id TEXT NOT NULL,
        reason TEXT NOT NULL,
        merged_by TEXT NOT NULL,
        merged_by_name TEXT NOT NULL,
        merged_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS import_jobs (
        id TEXT PRIMARY KEY,
        filename TEXT NOT NULL,
        owner_id TEXT NOT NULL,
        owner_name TEXT NOT NULL,
        total_rows INTEGER NOT NULL,
        created_count INTEGER NOT NULL,
        updated_count INTEGER NOT NULL DEFAULT 0,
        conflict_count INTEGER NOT NULL,
        error_count INTEGER NOT NULL,
        imported_by TEXT NOT NULL,
        imported_by_name TEXT NOT NULL,
        created_at TEXT NOT NULL,
        data_quality_json TEXT NOT NULL DEFAULT '{}',
        created_customer_ids_json TEXT NOT NULL DEFAULT '[]',
        updated_customer_ids_json TEXT NOT NULL DEFAULT '[]',
        opened_customer_ids_json TEXT NOT NULL DEFAULT '[]',
        review_items_json TEXT NOT NULL DEFAULT '[]',
        rolled_back_at TEXT,
        rolled_back_by TEXT
    )
    """,
    "ALTER TABLE import_jobs ADD COLUMN IF NOT EXISTS updated_count INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE import_jobs ADD COLUMN IF NOT EXISTS updated_customer_ids_json TEXT NOT NULL DEFAULT '[]'",
    "ALTER TABLE import_jobs ADD COLUMN IF NOT EXISTS opened_customer_ids_json TEXT NOT NULL DEFAULT '[]'",
    "ALTER TABLE import_jobs ADD COLUMN IF NOT EXISTS review_items_json TEXT NOT NULL DEFAULT '[]'",
    """
    CREATE TABLE IF NOT EXISTS audit_logs (
        id TEXT PRIMARY KEY,
        actor_id TEXT NOT NULL,
        actor_name TEXT NOT NULL,
        action TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        detail_json TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS placement_batches (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        product_name TEXT NOT NULL DEFAULT '定增项目',
        close_date TEXT,
        status TEXT NOT NULL DEFAULT '筹备中',
        target_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
        notes TEXT NOT NULL DEFAULT '',
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS customer_fields (
        id TEXT PRIMARY KEY,
        field_key TEXT NOT NULL UNIQUE,
        label TEXT NOT NULL,
        field_type TEXT NOT NULL,
        options_json TEXT NOT NULL DEFAULT '[]',
        active INTEGER NOT NULL DEFAULT 1,
        display_order INTEGER NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_by TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_fields_label_ci ON customer_fields(lower(label))",
    """
    CREATE TABLE IF NOT EXISTS customer_field_values (
        customer_id TEXT NOT NULL REFERENCES customers(id) DEFERRABLE INITIALLY DEFERRED,
        field_id TEXT NOT NULL REFERENCES customer_fields(id) DEFERRABLE INITIALLY DEFERRED,
        value_text TEXT NOT NULL DEFAULT '',
        updated_by TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (customer_id, field_id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_customer_field_values_field ON customer_field_values(field_id, customer_id)",
    """
    CREATE TABLE IF NOT EXISTS customer_holding_snapshots (
        id TEXT PRIMARY KEY,
        customer_id TEXT NOT NULL REFERENCES customers(id) DEFERRABLE INITIALLY DEFERRED,
        snapshot_date TEXT NOT NULL,
        security_name TEXT NOT NULL DEFAULT '二级市场持仓',
        quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
        market_value DOUBLE PRECISION NOT NULL DEFAULT 0,
        source_label TEXT NOT NULL DEFAULT '',
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(customer_id, snapshot_date, security_name)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_holding_snapshots_customer_date ON customer_holding_snapshots(customer_id, snapshot_date DESC)",
]
